"""
app/tokens.py — Short-lived in-memory token store for watchlist auth.

Tokens are generated by the LINE bot (我的清單 command) and validated
by the /watchlist web route.  Tokens are process-local: they survive
hot-reloads but not process restarts (acceptable — Render Free Tier
restarts occasionally, tokens are intentionally short-lived).

TTL: 30 minutes.  Expired tokens are purged lazily on each write.
"""
from __future__ import annotations

import secrets
import time

_store: dict[str, tuple[str, float]] = {}  # token -> (user_id, expires_at)
_TTL = 1800  # 30 minutes in seconds


def _purge() -> None:
    """Remove all expired entries (called on every create to prevent unbounded growth)."""
    now = time.time()
    expired = [k for k, (_, exp) in _store.items() if now > exp]
    for k in expired:
        del _store[k]


def create_token(user_id: str) -> str:
    """Generate a new URL-safe token tied to user_id and store it with a 30-min TTL."""
    _purge()
    token = secrets.token_urlsafe(16)
    _store[token] = (user_id, time.time() + _TTL)
    return token


def validate_token(token: str) -> str | None:
    """Return user_id if token is valid and not expired; else None (and remove it)."""
    entry = _store.get(token)
    if entry is None:
        return None
    user_id, expires = entry
    if time.time() > expires:
        del _store[token]
        return None
    return user_id
